version: '2.4'
services:
  pgRouting:
    image: tommilehtisaari/digiroad-db:5_2019_uusimaa_2
    environment:
      POSTGRES_PASSWORD: superSecretPassword
      POSTGRES_DB: 'dr_r'
    volumes:
      - digiroadPostgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -h 127.0.0.1

  asset-matcher:
    image: tommilehtisaari/digiroad-asset-matcher:sha-76da7f3
    environment:
      PG_HOST: 'pgRouting'
      PG_PORT: 5432
      PG_USER: 'postgres'
      PG_PASSWORD: superSecretPassword
      PG_DATABASE: 'dr_r'
    ports:
      - 3000:3000
    depends_on:
      pgRouting:
        condition: service_healthy

volumes:
  digiroadPostgres:
